EX3: factori.c File Reference
factori.c File Reference
Main program file. Factori will receive 4 command arguments: Task file, priority file, number of tasks, and number of threads. It then Will compute the prime factors of the target numbers in the tasks file, in the order mentioned in the pririty file. It will then add to the task file a string with the prime factors of the target number. It will do that using the mentioned number of threads, which means, the output order is not gurnteed when ran with more than one thread. The main thread will read the priority file and set the priorities into a FIFO queue. After that the main thread will start N worker threads. At their own pace each worker will pop an task, read it from database file, compute the prime factors, and write the factors to end of the file. Access to shared resources is protect using mutexes and semaphores by the lock module.
#include "factori.h"
Functions
int main (int argc, char *argv[])
< When we want to test a specific function/ scenario compile with that flag, when done, we compile another file with cutsom tests.
static error_e create_worker (HANDLE *p_worker_handle, worker_params_t *p_worker_param)
Create a worker object: Packs parameters into a struct, and calls CreateThread.
static DWORD WINAPI worker_thread (LPVOID lpParam)
As the name suggests, does most of the work load expected from the program. Details are found in the readme.md file and in the brief of this entire file.
Detailed Description
Main program file. Factori will receive 4 command arguments: Task file, priority file, number of tasks, and number of threads. It then Will compute the prime factors of the target numbers in the tasks file, in the order mentioned in the pririty file. It will then add to the task file a string with the prime factors of the target number. It will do that using the mentioned number of threads, which means, the output order is not gurnteed when ran with more than one thread. The main thread will read the priority file and set the priorities into a FIFO queue. After that the main thread will start N worker threads. At their own pace each worker will pop an task, read it from database file, compute the prime factors, and write the factors to end of the file. Access to shared resources is protect using mutexes and semaphores by the lock module.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file factori.c.
Function Documentation
create_worker()
static error_e create_worker (HANDLE * p_worker_handle, worker_params_t * p_worker_param) static
Create a worker object: Packs parameters into a struct, and calls CreateThread.
Parameters
p_worker_handle : A pointer to an handle, fills it with allocated handle, will be used by caller to close handle.
p_worker_param : String containg the task file name, Pointer to queue.
Returns
error_e
Definition at line 243 of file factori.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT_ARG("Input file name : %s\n", p_worker_param->a_tasks_file_name);
     DEBUG_PRINT_QUEUE_STATUS(p_worker_param->p_queue);
     error_e e_status = ERROR_OK;
     if( (NULL == p_worker_handle)                  ||
         (NULL == p_worker_param)                   ||
         (NULL == p_worker_param->p_queue)          ||
         (NULL == p_worker_param->a_tasks_file_name)||
         (NULL == p_worker_param->p_lock_queue)     ||
         (NULL == p_worker_param->p_lock_tasks_file)
         )
     {
         print_error_msg("Recieved invalid parameters!\n");
         e_status = ERROR_INVALID_PARAM_E;
     }
     else
     {
         LPDWORD p_thread_id = NULL;
         (*p_worker_handle) = CreateThread(
             NULL,                               /*  default security attributes */
             0,                                  /*  use default stack size */
             worker_thread,                      /*  thread function */
             p_worker_param,                     /*  argument to thread function */
             0,                                  /*  use default creation flags */
             p_thread_id);                       /*  returns the thread identifier */
         if (NULL == (*p_worker_handle))
         {
             print_error_msg("Error when creating thread\n");
             e_status = ERROR_FAILED_TO_CREATE_THREAD_E;
         }
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References worker_params_s::a_tasks_file_name, DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, DEBUG_PRINT_QUEUE_STATUS, ERROR_FAILED_TO_CREATE_THREAD_E, ERROR_INVALID_PARAM_E, ERROR_OK, worker_params_s::p_lock_queue, worker_params_s::p_lock_tasks_file, worker_params_s::p_queue, print_error_msg, and worker_thread().
Referenced by main().
main()
int main (int argc, char * argv[])
< When we want to test a specific function/ scenario compile with that flag, when done, we compile another file with cutsom tests.
Parameters
[in] argc
[in] argv
Returns
int
< A pointer to the queue which will hold the task offsets in the task file.
< A pointer to the lock which will hold the synchronization enteties: mutexes and semaphores..
< A pointer to the lock which will hold the synchronization enteties: mutexes and semaphores..
< The priority file handle
< The task file handle
< A pointer to an array of HANDLE for the "workers" - threads that will process the tasks.
Definition at line 35 of file factori.c.
 {
     /*------------------------------
     * Declare variables
     * ---------------------------*/
     error_e e_status;
     factori_args_t command_line_args;
     queue_t         *p_task_priority_queue      = NULL;
     lock_t          *p_lock_queue               = NULL;
     lock_t          *p_lock_tasks_file          = NULL;
     HANDLE          priority_file_handle        = NULL;
     HANDLE          task_file_handle            = NULL;
     HANDLE          *pa_working_threads_handles = NULL;
     worker_params_t *p_workers_params           = NULL;
     do
     {
         /*------------------------------
         * Parse command line to parameters
         * ---------------------------*/
         e_status = parse_command_line_input(argc, argv, &command_line_args);
         CHECK_AND_BREAK(e_status);
         if (command_line_args.num_of_threads == 0)
         {
             break;
         }
         /*------------------------------
         * Initialize priority queue
         * ---------------------------*/
         // Init queue struct
         p_task_priority_queue = QUEUE_initialize_queue();
         if(NULL == p_task_priority_queue)
         {
             e_status = ERROR_FAILES_TO_INITIALIZE_QUEUE_E;
         }
         CHECK_AND_BREAK(e_status);
         // Init lock struct
         p_lock_queue = LOCK_initialize_lock();
         if(NULL == p_lock_queue)
         {
             print_error_msg("Failed to initialize queue lock!\n");
             e_status = ERROR_FAILES_TO_INITIALIZE_LOCK_E;
         }
         CHECK_AND_BREAK(e_status);
         p_lock_tasks_file = LOCK_initialize_lock();
         if(NULL == p_lock_tasks_file)
         {
             print_error_msg("Failed to initialize tasks file lock!\n");
             e_status = ERROR_FAILES_TO_INITIALIZE_LOCK_E;
         }
         CHECK_AND_BREAK(e_status);
         // Open priority file
         e_status = FILE_UTILS_create_file_for_shared_read_and_write(&priority_file_handle, command_line_args.p_priority_file_name);
         CHECK_AND_BREAK(e_status);
         const DWORD priorities_file_size = GetFileSize(priority_file_handle, NULL);
         // for each line, read the line digits, convert to a number and add it to queue
         DWORD        current_position = 0;
         DWORD        bytes_read       = 0;
         queue_elem_t new_element      = NULL_QUEUE_ELEMENT;
         while(current_position < priorities_file_size)
         {
             e_status = FILE_UTILS_read_one_line_from_file(priority_file_handle, &bytes_read, &new_element.data);
             CHECK_AND_BREAK(e_status);
             e_status =  QUEUE_push(p_task_priority_queue, new_element);
             CHECK_AND_BREAK(e_status);
             current_position += bytes_read;
         }
         CHECK_AND_BREAK(e_status);
         // get task file size, will be used to read line by line (ReadFile does not stop at EOF)
         e_status = FILE_UTILS_create_file_for_shared_read_and_write(&task_file_handle, command_line_args.a_task_file_name);
         CHECK_AND_BREAK(e_status);
         const DWORD tasks_file_size = GetFileSize(task_file_handle, NULL);
         if(task_file_handle && (task_file_handle != INVALID_HANDLE_VALUE))
         {
             CloseHandle(task_file_handle);
             task_file_handle = NULL;
         }
         FILE_UTILS_set_write_position(tasks_file_size);
         /*------------------------------
         * Call workers (threads)
         * ---------------------------*/
         if (command_line_args.num_of_threads == 0)
         {
             break;
         }
         pa_working_threads_handles = malloc(command_line_args.num_of_threads * sizeof(HANDLE));
         if(NULL == pa_working_threads_handles)
         {
             print_error_msg("Failed to allocate memory for workers handles\n");
             e_status = ERROR_FAILED_TO_ALLOCATE_MEMORY_E;
         }
         CHECK_AND_BREAK(e_status);
         p_workers_params           = malloc(command_line_args.num_of_threads * sizeof(worker_params_t));
         if(NULL == p_workers_params)
         {
             print_error_msg("Failed to allocate memory for workers params\n");
             e_status = ERROR_FAILED_TO_ALLOCATE_MEMORY_E;
         }
         CHECK_AND_BREAK(e_status);
         DEBUG_PRINT(DEBUG_LEVEL_FIVE, "Starting to call workers. Total number: %d\n", command_line_args.num_of_threads);
         for(DWORD worker_idx = 0; worker_idx < command_line_args.num_of_threads; worker_idx++)
         {
             if (command_line_args.num_of_threads != 0)
             {
                 errno_t strcpy_status = strcpy_s(p_workers_params[worker_idx].a_tasks_file_name, MAX_PATH, command_line_args.a_task_file_name);
                 if(strcpy_status)
                 {
                     print_error_msg("Failed to copy string of task file\n")
                     e_status = ERROR_STRCPY_FAILED_E;
                 }
                 CHECK_AND_BREAK(e_status);
                 p_workers_params[worker_idx].p_queue              = p_task_priority_queue;
                 p_workers_params[worker_idx].p_lock_queue         = p_lock_queue;
                 p_workers_params[worker_idx].p_lock_tasks_file    = p_lock_tasks_file;
                 pa_working_threads_handles[worker_idx]            = NULL;
                 e_status = create_worker(&pa_working_threads_handles[worker_idx], &p_workers_params[worker_idx]);
             }
             CHECK_AND_BREAK(e_status);
         }
         CHECK_AND_BREAK(e_status);
     } while (FALSE);
     /*------------------------------
     * Cleanup: Free memory, Close handles
     * ---------------------------*/
     if(pa_working_threads_handles)
     {
         DWORD status = WaitForMultipleObjects(command_line_args.num_of_threads, pa_working_threads_handles, TRUE, FIVE_MINUTES_IN_MILLISECONDS);
         DEBUG_PRINT(DEBUG_LEVEL_ONE, "WaitForMultipleObjects returned with status: %d\n", status);
         for(DWORD worker_idx = 0; worker_idx < command_line_args.num_of_threads; worker_idx++)
         {
             if(pa_working_threads_handles[worker_idx])
             {
                 BOOL get_exit_code_stat = GetExitCodeThread(
                     pa_working_threads_handles[worker_idx],
                     (LPDWORD)(&e_status)
                     );
                 if(FALSE == get_exit_code_stat)
                 {
                     e_status = ERROR_FAILED_TO_GET_THREAD_EXIT_CODE_E;
                     print_error_msg("Failed to get thread %d exit code\n", worker_idx);
                 }
             }
         }
         for(DWORD worker_idx = 0; worker_idx < command_line_args.num_of_threads; worker_idx++)
         {
             if(pa_working_threads_handles[worker_idx])
             {
                 CloseHandle(pa_working_threads_handles[worker_idx]);
                 pa_working_threads_handles[worker_idx] = NULL;
             }
         }
         free(pa_working_threads_handles);
     }
     if(p_task_priority_queue)
     {
         e_status += QUEUE_destroy_queue(&p_task_priority_queue);
     }
     if(p_lock_tasks_file)
     {
         e_status += LOCK_destroy_lock(&p_lock_tasks_file);
     }
     if(p_lock_queue)
     {
         e_status += LOCK_destroy_lock(&p_lock_queue);
     }
     if(priority_file_handle)
     {
         CloseHandle(priority_file_handle);
         priority_file_handle = NULL;
     }
     if(task_file_handle && (task_file_handle != INVALID_HANDLE_VALUE))
     {
         CloseHandle(task_file_handle);
         task_file_handle = NULL;
     }
     if(p_workers_params)
     {
         free(p_workers_params);
     }
     return e_status;
 }
References factori_args_s::a_task_file_name, CHECK_AND_BREAK, create_worker(), queue_elem_s::data, DEBUG_LEVEL_FIVE, DEBUG_LEVEL_ONE, DEBUG_PRINT, ERROR_FAILED_TO_ALLOCATE_MEMORY_E, ERROR_FAILED_TO_GET_THREAD_EXIT_CODE_E, ERROR_FAILES_TO_INITIALIZE_LOCK_E, ERROR_FAILES_TO_INITIALIZE_QUEUE_E, ERROR_STRCPY_FAILED_E, FILE_UTILS_create_file_for_shared_read_and_write(), FILE_UTILS_read_one_line_from_file(), FILE_UTILS_set_write_position(), FIVE_MINUTES_IN_MILLISECONDS, LOCK_destroy_lock(), LOCK_initialize_lock(), NULL_QUEUE_ELEMENT, factori_args_s::num_of_threads, worker_params_s::p_lock_queue, worker_params_s::p_lock_tasks_file, factori_args_s::p_priority_file_name, worker_params_s::p_queue, parse_command_line_input(), print_error_msg, QUEUE_destroy_queue(), QUEUE_initialize_queue(), and QUEUE_push().
worker_thread()
static DWORD WINAPI worker_thread (LPVOID lpParam) static
As the name suggests, does most of the work load expected from the program. Details are found in the readme.md file and in the brief of this entire file.
Parameters
lpParam
Returns
DWORD
Definition at line 296 of file factori.c.
 {
     // Debug Prefix /////////////
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK;
     worker_params_t *p_worker_params = (worker_params_t*)lpParam;
     HANDLE tasks_file_handle = NULL;
     char* p_output_buffer = NULL;
     queue_elem_t task_position = {0};
     do
     {
         // Open task file for reading
         e_status = FILE_UTILS_create_file_for_shared_read_and_write(&tasks_file_handle, p_worker_params->a_tasks_file_name);
         CHECK_AND_BREAK(e_status);
         while(TRUE)
         {
             e_status = LOCK_write_lock(p_worker_params->p_lock_queue);
             CHECK_AND_BREAK(e_status);
             BOOL b_is_empty = QUEUE_empty(p_worker_params->p_queue);
             if(FALSE == b_is_empty)
             {
                 task_position = QUEUE_top(p_worker_params->p_queue);
                 e_status = QUEUE_pop(p_worker_params->p_queue);
                 CHECK_AND_BREAK(e_status);
             }
             else
             {
                 e_status = LOCK_write_release(p_worker_params->p_lock_queue);
                 CHECK_AND_BREAK(e_status);
                 break;
             }
             e_status = LOCK_write_release(p_worker_params->p_lock_queue);
             CHECK_AND_BREAK(e_status);
             SetFilePointer(tasks_file_handle, task_position.data, NULL, FILE_BEGIN);
             DWORD bytes_read_from_file;
             DWORD target_number;
             e_status = LOCK_read_lock(p_worker_params->p_lock_tasks_file);
             CHECK_AND_BREAK(e_status);
             e_status = FILE_UTILS_read_one_line_from_file(tasks_file_handle, &bytes_read_from_file, &target_number);
             CHECK_AND_BREAK(e_status);
             e_status = LOCK_read_release(p_worker_params->p_lock_tasks_file);
             CHECK_AND_BREAK(e_status);
             DEBUG_PRINT(DEBUG_LEVEL_FIVE, "Thread id: %d, Starting work on target num: %d\n", GetCurrentThreadId(), target_number);
             DWORD primes_array[MAX_NUMBER_OF_PRIMES] = {0};
             DWORD number_of_primes = 0;
             e_status = PRIME_get_primes(target_number, primes_array, &number_of_primes);
             CHECK_AND_BREAK(e_status);
             DWORD bytes_in_line = 0;
             p_output_buffer = (char*)malloc((CHAR_SIZE_OF_FIRST_LINE + (MAX_NUMBER_OF_DIGITS+CHAR_SIZE_OF_LINE_FOR_EACH_PRIME)*(number_of_primes + 1))*sizeof(char));
             if (NULL == p_output_buffer)
             {
                 print_error_msg("Malloc for p_output_buffer failed\n");
                 e_status = ERROR_FAILED_TO_ALLOCATE_MEMORY_E;
             }
             CHECK_AND_BREAK(e_status);
             e_status = create_output_line(target_number, primes_array, number_of_primes, p_output_buffer, &bytes_in_line);
             CHECK_AND_BREAK(e_status);
             e_status = LOCK_write_lock(p_worker_params->p_lock_tasks_file);
             CHECK_AND_BREAK(e_status);
             e_status = FILE_UTILS_write_buffer_to_file(tasks_file_handle, p_output_buffer, bytes_in_line);
             CHECK_AND_BREAK(e_status);
             e_status = LOCK_write_release(p_worker_params->p_lock_tasks_file);
             CHECK_AND_BREAK(e_status);
         }
     } while (FALSE);
     /*------------------------------
     * Cleanup: Free memory, Close handles
     * ----------------------------*/
     if(tasks_file_handle && (tasks_file_handle != INVALID_HANDLE_VALUE))
     {
         CloseHandle(tasks_file_handle);
         tasks_file_handle = NULL;
     }
     if (p_output_buffer)
     {
         free(p_output_buffer);
     }
     // Debug Suffix /////////////
     DEBUG_PRINT_FUNCTION_END();
     return (DWORD)e_status;
 }
References worker_params_s::a_tasks_file_name, CHAR_SIZE_OF_FIRST_LINE, CHAR_SIZE_OF_LINE_FOR_EACH_PRIME, CHECK_AND_BREAK, create_output_line(), queue_elem_s::data, DEBUG_LEVEL_FIVE, DEBUG_PRINT, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, ERROR_FAILED_TO_ALLOCATE_MEMORY_E, ERROR_OK, FILE_UTILS_create_file_for_shared_read_and_write(), FILE_UTILS_read_one_line_from_file(), FILE_UTILS_write_buffer_to_file(), LOCK_read_lock(), LOCK_read_release(), LOCK_write_lock(), LOCK_write_release(), MAX_NUMBER_OF_DIGITS, MAX_NUMBER_OF_PRIMES, worker_params_s::p_lock_queue, worker_params_s::p_lock_tasks_file, worker_params_s::p_queue, PRIME_get_primes(), print_error_msg, QUEUE_empty(), QUEUE_pop(), and QUEUE_top().
Referenced by create_worker().